### ISSUE TITLE
Requirement of the MessageBundle

### ISSUE THREAD

**Issue by GauthLin** [claroline/AnnouncementBundle#24]
Hi,
The AnnouncementBundle requires a service that is in the MessageBundle. So, if the MessageBundle isn't install an error appears. Maybey, simply add a requirement in the composer.json to avoid this error.

![announcementbundle requires messagebundle](https://cloud.githubusercontent.com/assets/11615403/7343646/314b6388-ecc4-11e4-91e4-3db54cf09092.png)

Gauthier

**Comment by kitan1982** [comment]
I have removed the reference to MessageBundle.
Now a message can be sent by generating an event. (SendMessageEvent)
